// Regenerates public/sitemap.xml from the actual route table and product list.
//
// Written as a generator rather than a hand-maintained file because the previous
// sitemap listed only the 8 static pages per locale and none of the product
// detail pages — which are the highest-intent pages on the site ("Russian wheat
// supplier" and friends). Hand-editing 34 extra URLs guarantees future drift.
//
// Run: pnpm --filter @workspace/alaa-agro run gen:sitemap

import fs from "node:fs";
import path from "node:path";

const ORIGIN = "https://alaa-argo.com";
const LOCALES = ["en", "ru"];
const DEFAULT_LOCALE = "en";

const pkgRoot = path.resolve(import.meta.dirname, "..");

// Routes as declared in src/App.tsx, minus InsightsPage which has no <Route>.
const STATIC_PATHS = [
  "",
  "/products",
  "/about",
  "/quality",
  "/packaging",
  "/trade",
  "/quote",
  "/contact",
];

const productsSrc = fs.readFileSync(
  path.join(pkgRoot, "src/data/products.ts"),
  "utf8",
);
const slugs = [...productsSrc.matchAll(/\bslug:\s*"([^"]+)"/g)].map((m) => m[1]);

if (slugs.length === 0) {
  throw new Error("No product slugs found in src/data/products.ts");
}

const paths = [...STATIC_PATHS, ...slugs.map((s) => `/products/${s}`)];

const urls = LOCALES.flatMap((locale) =>
  paths.map((p) => {
    const alternates = [
      ...LOCALES.map(
        (l) =>
          `    <xhtml:link rel="alternate" hreflang="${l}" href="${ORIGIN}/${l}${p}" />`,
      ),
      `    <xhtml:link rel="alternate" hreflang="x-default" href="${ORIGIN}/${DEFAULT_LOCALE}${p}" />`,
    ].join("\n");

    return `  <url>\n    <loc>${ORIGIN}/${locale}${p}</loc>\n${alternates}\n  </url>`;
  }),
);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join("\n")}
</urlset>
`;

const out = path.join(pkgRoot, "public/sitemap.xml");
fs.writeFileSync(out, xml);

console.log(
  `sitemap.xml: ${urls.length} URLs ` +
    `(${LOCALES.length} locales x ${paths.length} paths, ` +
    `${slugs.length} of them products)`,
);
